# Generated by Django 3.2.11 on 2022-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
