# Generated by Django 3.2.11 on 2022-01-23 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dev_App', '0002_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
