# Generated by Django 3.2.11 on 2022-01-24 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dev_App', '0003_auto_20220123_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
